#automatically generated by bfconvertor.nas
var ptr=0;
var paper=[];
setsize(paper,131072);
while(paper[ptr]) {
}
paper[ptr]+=13;
while(paper[ptr]) {
  paper[ptr]-=1;
  ptr+=1;
  paper[ptr]+=2;
  ptr+=3;
  paper[ptr]+=5;
  ptr+=1;
  paper[ptr]+=2;
  ptr+=1;
  paper[ptr]+=1;
  ptr-=6;
}
ptr+=5;
paper[ptr]+=6;
ptr+=1;
paper[ptr]-=3;
ptr+=10;
paper[ptr]+=15;
while(paper[ptr]) {
  while(paper[ptr]) {
    ptr+=9;
  }
  paper[ptr]+=1;
  while(paper[ptr]) {
    ptr-=9;
  }
  ptr+=9;
  paper[ptr]-=1;
}
paper[ptr]+=1;
while(paper[ptr]) {
  ptr+=8;
  while(paper[ptr]) {
    paper[ptr]-=1;
  }
  ptr+=1;
}
ptr-=9;
while(paper[ptr]) {
  ptr-=9;
}
ptr+=8;
while(paper[ptr]) {
  paper[ptr]-=1;
}
paper[ptr]+=1;
ptr-=7;
paper[ptr]+=5;
while(paper[ptr]) {
  paper[ptr]-=1;
  while(paper[ptr]) {
    paper[ptr]-=1;
    ptr+=9;
    paper[ptr]+=1;
    ptr-=9;
  }
  ptr+=9;
}
ptr+=7;
paper[ptr]+=1;
ptr+=27;
paper[ptr]+=1;
ptr-=17;
while(paper[ptr]) {
  ptr-=9;
}
ptr+=3;
while(paper[ptr]) {
  paper[ptr]-=1;
}
paper[ptr]+=1;
while(paper[ptr]) {
  ptr+=6;
  while(paper[ptr]) {
    ptr+=7;
    while(paper[ptr]) {
      paper[ptr]-=1;
    }
    ptr+=2;
  }
  ptr-=9;
  while(paper[ptr]) {
    ptr-=9;
  }
  ptr+=7;
  while(paper[ptr]) {
    paper[ptr]-=1;
  }
  paper[ptr]+=1;
  ptr-=6;
  paper[ptr]+=4;
  while(paper[ptr]) {
    paper[ptr]-=1;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr+=9;
      paper[ptr]+=1;
      ptr-=9;
    }
    ptr+=9;
  }
  ptr+=6;
  paper[ptr]+=1;
  ptr-=6;
  paper[ptr]+=7;
  while(paper[ptr]) {
    paper[ptr]-=1;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr+=9;
      paper[ptr]+=1;
      ptr-=9;
    }
    ptr+=9;
  }
  ptr+=6;
  paper[ptr]+=1;
  ptr-=16;
  while(paper[ptr]) {
    ptr-=9;
  }
  ptr+=3;
  while(paper[ptr]) {
    while(paper[ptr]) {
      paper[ptr]-=1;
    }
    ptr+=6;
    while(paper[ptr]) {
      ptr+=7;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=6;
        paper[ptr]+=1;
        ptr+=6;
      }
      ptr-=6;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=6;
        paper[ptr]+=1;
        ptr-=2;
        paper[ptr]+=1;
        ptr-=3;
        paper[ptr]+=1;
        ptr-=1;
      }
      ptr+=8;
    }
    ptr-=9;
    while(paper[ptr]) {
      ptr-=9;
    }
    ptr+=9;
    while(paper[ptr]) {
      ptr+=8;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=7;
        paper[ptr]+=1;
        ptr+=7;
      }
      ptr-=7;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=7;
        paper[ptr]+=1;
        ptr-=2;
        paper[ptr]+=1;
        ptr-=3;
        paper[ptr]+=1;
        ptr-=2;
      }
      ptr+=8;
    }
    ptr-=9;
    while(paper[ptr]) {
      ptr-=9;
    }
    ptr+=7;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr-=7;
      paper[ptr]+=1;
      ptr+=7;
    }
    ptr-=7;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr+=7;
      paper[ptr]+=1;
      ptr-=2;
      paper[ptr]+=1;
      ptr-=5;
    }
    ptr+=9;
    paper[ptr]+=15;
    while(paper[ptr]) {
      while(paper[ptr]) {
        ptr+=9;
      }
      paper[ptr]+=1;
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      paper[ptr]-=1;
    }
    paper[ptr]+=1;
    while(paper[ptr]) {
      ptr+=1;
      paper[ptr]+=1;
      ptr+=8;
    }
    ptr-=9;
    while(paper[ptr]) {
      ptr-=9;
    }
    ptr+=9;
    while(paper[ptr]) {
      ptr+=1;
      paper[ptr]-=1;
      ptr+=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=4;
        paper[ptr]+=1;
        ptr+=4;
      }
      ptr-=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=4;
        paper[ptr]+=1;
        ptr-=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=2;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=2;
            paper[ptr]+=1;
            ptr+=2;
          }
          ptr-=2;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=2;
            paper[ptr]+=1;
            ptr+=2;
            paper[ptr]+=1;
            ptr-=4;
          }
          paper[ptr]+=1;
          ptr+=9;
        }
        ptr-=8;
        while(paper[ptr]) {
          ptr-=9;
        }
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=9;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=9;
          paper[ptr]+=1;
          ptr-=9;
        }
        ptr-=10;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=9;
        paper[ptr]+=1;
        ptr-=9;
      }
      ptr-=1;
      paper[ptr]+=1;
      ptr+=8;
    }
    ptr-=9;
    while(paper[ptr]) {
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr-=1;
      paper[ptr]-=1;
      ptr+=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=4;
        paper[ptr]+=1;
        ptr+=1;
        while(paper[ptr]) {
          ptr-=1;
          paper[ptr]-=1;
          ptr+=1;
          paper[ptr]-=1;
          ptr-=6;
          paper[ptr]+=1;
          ptr+=6;
        }
        ptr-=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=1;
          paper[ptr]+=1;
          ptr-=1;
        }
        ptr+=4;
      }
      ptr-=3;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=3;
        paper[ptr]+=1;
        ptr-=3;
      }
      ptr-=1;
      paper[ptr]+=1;
      ptr-=9;
    }
    ptr+=9;
    while(paper[ptr]) {
      ptr+=1;
      paper[ptr]+=1;
      ptr+=8;
    }
    ptr-=9;
    while(paper[ptr]) {
      ptr-=9;
    }
    ptr+=9;
    while(paper[ptr]) {
      ptr+=1;
      paper[ptr]-=1;
      ptr+=5;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=5;
        paper[ptr]+=1;
        ptr+=5;
      }
      ptr-=5;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=5;
        paper[ptr]+=1;
        ptr-=6;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=3;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=3;
            paper[ptr]+=1;
            ptr+=3;
          }
          ptr-=3;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=3;
            paper[ptr]+=1;
            ptr+=1;
            paper[ptr]+=1;
            ptr-=4;
          }
          paper[ptr]+=1;
          ptr+=9;
        }
        ptr-=8;
        while(paper[ptr]) {
          ptr-=9;
        }
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=9;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr+=2;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=9;
          paper[ptr]+=1;
          ptr-=9;
        }
        ptr-=11;
      }
      ptr+=2;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=9;
        paper[ptr]+=1;
        ptr-=9;
      }
      ptr-=2;
      paper[ptr]+=1;
      ptr+=8;
    }
    ptr-=9;
    while(paper[ptr]) {
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr-=1;
      paper[ptr]-=1;
      ptr+=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=4;
        paper[ptr]+=1;
        ptr+=1;
        while(paper[ptr]) {
          ptr-=1;
          paper[ptr]-=1;
          ptr+=1;
          paper[ptr]-=1;
          ptr-=6;
          paper[ptr]+=1;
          ptr+=6;
        }
        ptr-=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=1;
          paper[ptr]+=1;
          ptr-=1;
        }
        ptr+=4;
      }
      ptr-=3;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=3;
        paper[ptr]+=1;
        ptr-=3;
      }
      ptr-=1;
      paper[ptr]+=1;
      ptr-=9;
    }
    ptr+=9;
    while(paper[ptr]) {
      ptr+=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=36;
        paper[ptr]+=1;
        ptr+=36;
      }
      ptr+=5;
    }
    ptr-=9;
    while(paper[ptr]) {
      ptr-=9;
    }
    ptr+=9;
    paper[ptr]+=15;
    while(paper[ptr]) {
      while(paper[ptr]) {
        ptr+=9;
      }
      ptr-=9;
      paper[ptr]-=1;
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      paper[ptr]-=1;
    }
    paper[ptr]+=1;
    ptr+=21;
    paper[ptr]+=1;
    ptr-=3;
    while(paper[ptr]) {
      ptr-=9;
    }
    ptr+=9;
    while(paper[ptr]) {
      ptr+=3;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=3;
        paper[ptr]-=1;
        ptr+=3;
      }
      paper[ptr]+=1;
      ptr-=3;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=3;
        paper[ptr]-=1;
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=4;
          paper[ptr]+=1;
          ptr+=4;
        }
        ptr-=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=4;
          paper[ptr]+=1;
          ptr-=13;
          while(paper[ptr]) {
            ptr-=9;
          }
          ptr+=4;
          while(paper[ptr]) {
            paper[ptr]-=1;
          }
          paper[ptr]+=1;
          ptr+=5;
          while(paper[ptr]) {
            ptr+=9;
          }
          ptr+=1;
          paper[ptr]+=1;
          ptr-=1;
        }
      }
      paper[ptr]+=1;
      ptr+=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=4;
        paper[ptr]-=1;
        ptr+=4;
      }
      paper[ptr]+=1;
      ptr-=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=4;
        paper[ptr]-=1;
        ptr-=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=3;
          paper[ptr]+=1;
          ptr+=3;
        }
        ptr-=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=3;
          paper[ptr]+=1;
          ptr-=12;
          while(paper[ptr]) {
            ptr-=9;
          }
          ptr+=3;
          while(paper[ptr]) {
            paper[ptr]-=1;
          }
          paper[ptr]+=1;
          ptr+=6;
          while(paper[ptr]) {
            ptr+=9;
          }
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
          }
          paper[ptr]+=1;
          ptr-=1;
        }
      }
      paper[ptr]+=1;
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=1;
        while(paper[ptr]) {
          ptr+=9;
        }
        ptr-=8;
      }
      ptr+=8;
    }
    ptr-=9;
    while(paper[ptr]) {
      ptr-=9;
    }
    ptr-=7;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr+=1;
      paper[ptr]+=1;
      ptr+=3;
      paper[ptr]-=1;
      ptr-=4;
    }
    ptr+=9;
    paper[ptr]+=26;
    ptr+=2;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr-=4;
      paper[ptr]+=1;
      ptr+=4;
    }
    ptr-=4;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr+=4;
      paper[ptr]+=1;
      ptr-=2;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr-=2;
    }
    ptr+=2;
    while(paper[ptr]) {
      ptr-=7;
      paper[ptr]+=1;
      ptr-=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=1;
        paper[ptr]+=1;
        ptr+=4;
        paper[ptr]+=1;
        ptr-=2;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=2;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=1;
          paper[ptr]+=1;
          ptr+=3;
          paper[ptr]-=1;
          ptr-=4;
        }
        ptr+=3;
      }
      ptr+=13;
      while(paper[ptr]) {
        ptr+=2;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=5;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=3;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=6;
      while(paper[ptr]) {
        ptr+=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=4;
          paper[ptr]+=1;
          ptr+=4;
        }
        ptr-=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=4;
          paper[ptr]+=1;
          ptr-=3;
          paper[ptr]+=1;
          ptr-=1;
        }
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=2;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=9;
          paper[ptr]+=1;
          ptr+=9;
        }
        ptr+=7;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      paper[ptr]+=15;
      while(paper[ptr]) {
        while(paper[ptr]) {
          ptr+=9;
        }
        paper[ptr]+=1;
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr-=9;
        while(paper[ptr]) {
          ptr-=9;
        }
        ptr+=9;
        paper[ptr]-=1;
      }
      paper[ptr]+=1;
      while(paper[ptr]) {
        ptr+=1;
        paper[ptr]+=1;
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=1;
        paper[ptr]-=1;
        ptr+=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=5;
          paper[ptr]+=1;
          ptr+=5;
        }
        ptr-=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=5;
          paper[ptr]+=1;
          ptr-=6;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=2;
              paper[ptr]+=1;
              ptr+=2;
            }
            ptr-=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=2;
              paper[ptr]+=1;
              ptr+=1;
              paper[ptr]+=1;
              ptr-=3;
            }
            paper[ptr]+=1;
            ptr+=9;
          }
          ptr-=8;
          while(paper[ptr]) {
            ptr-=9;
          }
        }
        ptr+=9;
        while(paper[ptr]) {
          ptr+=9;
        }
        ptr-=9;
        while(paper[ptr]) {
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=9;
            paper[ptr]+=1;
            ptr-=9;
          }
          ptr-=10;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=9;
          paper[ptr]+=1;
          ptr-=9;
        }
        ptr-=1;
        paper[ptr]+=1;
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr-=1;
        paper[ptr]-=1;
        ptr+=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=3;
          paper[ptr]+=1;
          ptr+=1;
          while(paper[ptr]) {
            ptr-=1;
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]-=1;
            ptr-=7;
            paper[ptr]+=1;
            ptr+=7;
          }
          ptr-=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]+=1;
            ptr-=1;
          }
          ptr+=3;
        }
        ptr-=2;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=2;
          paper[ptr]+=1;
          ptr-=2;
        }
        ptr-=1;
        paper[ptr]+=1;
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=6;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=5;
          paper[ptr]+=1;
          ptr+=5;
        }
        ptr-=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=5;
          paper[ptr]+=1;
          ptr-=4;
          paper[ptr]+=1;
          ptr-=1;
        }
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=1;
        paper[ptr]+=1;
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=1;
        paper[ptr]-=1;
        ptr+=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=5;
          paper[ptr]+=1;
          ptr+=5;
        }
        ptr-=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=5;
          paper[ptr]+=1;
          ptr-=6;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=2;
              paper[ptr]+=1;
              ptr+=2;
            }
            ptr-=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=2;
              paper[ptr]+=1;
              ptr+=2;
              paper[ptr]+=1;
              ptr-=4;
            }
            paper[ptr]+=1;
            ptr+=9;
          }
          ptr-=8;
          while(paper[ptr]) {
            ptr-=9;
          }
        }
        ptr+=9;
        while(paper[ptr]) {
          ptr+=9;
        }
        ptr-=9;
        while(paper[ptr]) {
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=9;
            paper[ptr]+=1;
            ptr-=9;
          }
          ptr-=10;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=9;
          paper[ptr]+=1;
          ptr-=9;
        }
        ptr-=1;
        paper[ptr]+=1;
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr-=1;
        paper[ptr]-=1;
        ptr+=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=4;
          paper[ptr]+=1;
          ptr+=1;
          while(paper[ptr]) {
            ptr-=1;
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]-=1;
            ptr-=6;
            paper[ptr]+=1;
            ptr+=6;
          }
          ptr-=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]+=1;
            ptr-=1;
          }
          ptr+=4;
        }
        ptr-=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=3;
          paper[ptr]+=1;
          ptr-=3;
        }
        ptr-=1;
        paper[ptr]+=1;
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=36;
          paper[ptr]+=1;
          ptr+=36;
        }
        ptr+=5;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=36;
          paper[ptr]+=1;
          ptr+=36;
        }
        ptr+=6;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      paper[ptr]+=15;
      while(paper[ptr]) {
        while(paper[ptr]) {
          ptr+=9;
        }
        ptr-=9;
        paper[ptr]-=1;
        ptr-=9;
        while(paper[ptr]) {
          ptr-=9;
        }
        ptr+=9;
        paper[ptr]-=1;
      }
      paper[ptr]+=1;
      while(paper[ptr]) {
        ptr+=8;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=7;
          paper[ptr]+=1;
          ptr+=7;
        }
        ptr-=7;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=7;
          paper[ptr]+=1;
          ptr-=6;
          paper[ptr]+=1;
          ptr-=1;
        }
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=6;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=3;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=4;
      paper[ptr]+=1;
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=1;
        paper[ptr]-=1;
        ptr-=4;
        paper[ptr]+=1;
        ptr+=5;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=6;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=5;
          paper[ptr]+=1;
          ptr-=1;
          paper[ptr]+=2;
          ptr-=4;
        }
        ptr+=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=5;
          paper[ptr]+=1;
          ptr+=5;
        }
        ptr-=1;
        paper[ptr]-=1;
        ptr+=1;
        paper[ptr]+=1;
        ptr+=1;
      }
      ptr-=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=1;
        paper[ptr]+=1;
        ptr-=1;
      }
      ptr-=5;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=5;
        paper[ptr]+=1;
        ptr-=5;
      }
      ptr+=6;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr-=6;
      paper[ptr]+=1;
      ptr+=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=4;
        paper[ptr]-=1;
        ptr+=4;
      }
      paper[ptr]+=1;
      ptr-=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=4;
        paper[ptr]-=1;
        ptr+=5;
        while(paper[ptr]) {
          ptr+=2;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=2;
            paper[ptr]-=1;
            ptr+=2;
          }
          paper[ptr]+=1;
          ptr-=2;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=2;
            paper[ptr]-=1;
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=3;
              paper[ptr]+=1;
              ptr+=3;
            }
            ptr-=3;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=3;
              paper[ptr]+=1;
              ptr-=12;
              while(paper[ptr]) {
                ptr-=9;
              }
              ptr+=3;
              while(paper[ptr]) {
                paper[ptr]-=1;
              }
              paper[ptr]+=1;
              ptr+=6;
              while(paper[ptr]) {
                ptr+=9;
              }
              ptr+=1;
              paper[ptr]+=1;
              ptr-=1;
            }
          }
          paper[ptr]+=1;
          ptr+=3;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=3;
            paper[ptr]-=1;
            ptr+=3;
          }
          paper[ptr]+=1;
          ptr-=3;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=3;
            paper[ptr]-=1;
            ptr-=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=2;
              paper[ptr]+=1;
              ptr+=2;
            }
            ptr-=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=2;
              paper[ptr]+=1;
              ptr-=11;
              while(paper[ptr]) {
                ptr-=9;
              }
              ptr+=4;
              while(paper[ptr]) {
                paper[ptr]-=1;
              }
              paper[ptr]+=1;
              ptr+=5;
              while(paper[ptr]) {
                ptr+=9;
              }
              ptr+=1;
              while(paper[ptr]) {
                paper[ptr]-=1;
              }
              paper[ptr]+=1;
              ptr-=1;
            }
          }
          paper[ptr]+=1;
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=1;
            while(paper[ptr]) {
              ptr+=9;
            }
            ptr-=8;
          }
          ptr+=8;
        }
        ptr-=9;
        while(paper[ptr]) {
          ptr-=9;
        }
        ptr+=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=4;
          paper[ptr]+=1;
          ptr+=4;
        }
        ptr-=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=4;
          paper[ptr]+=1;
          ptr+=5;
          while(paper[ptr]) {
            ptr+=1;
            paper[ptr]+=1;
            ptr+=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=2;
              paper[ptr]-=1;
              ptr+=2;
            }
            ptr-=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=2;
              paper[ptr]+=1;
              ptr-=2;
            }
            ptr+=8;
          }
          ptr-=8;
          paper[ptr]+=1;
          ptr-=1;
          while(paper[ptr]) {
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=5;
              paper[ptr]+=1;
              ptr-=4;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr+=4;
                paper[ptr]-=1;
                ptr-=14;
                paper[ptr]+=1;
                ptr+=11;
                while(paper[ptr]) {
                  paper[ptr]-=1;
                  ptr+=3;
                  paper[ptr]+=1;
                  ptr-=3;
                }
                ptr-=1;
              }
              ptr+=1;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr+=3;
                paper[ptr]-=1;
                ptr-=14;
                paper[ptr]+=1;
                ptr+=11;
              }
              ptr-=2;
            }
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=4;
              paper[ptr]+=1;
              ptr-=3;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr+=3;
                paper[ptr]-=1;
                ptr-=14;
                paper[ptr]+=1;
                ptr+=11;
              }
              ptr-=1;
            }
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=3;
              paper[ptr]+=1;
              ptr-=3;
            }
            ptr-=12;
          }
          ptr+=4;
          while(paper[ptr]) {
            paper[ptr]-=1;
          }
          ptr-=4;
        }
        ptr+=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=3;
          paper[ptr]+=1;
          ptr+=3;
        }
        ptr-=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=3;
          paper[ptr]+=1;
          ptr+=6;
          while(paper[ptr]) {
            ptr+=1;
            paper[ptr]+=1;
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=1;
              paper[ptr]-=1;
              ptr+=1;
            }
            ptr-=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=1;
              paper[ptr]+=1;
              ptr-=1;
            }
            ptr+=8;
          }
          ptr-=8;
          paper[ptr]+=1;
          ptr-=1;
          while(paper[ptr]) {
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=5;
              paper[ptr]+=1;
              ptr-=3;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr+=3;
                paper[ptr]-=1;
                ptr-=14;
                paper[ptr]+=1;
                ptr+=10;
                while(paper[ptr]) {
                  paper[ptr]-=1;
                  ptr+=4;
                  paper[ptr]+=1;
                  ptr-=4;
                }
                ptr+=1;
              }
              ptr-=1;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr+=4;
                paper[ptr]-=1;
                ptr-=14;
                paper[ptr]+=1;
                ptr+=10;
              }
              ptr-=1;
            }
            ptr+=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=3;
              paper[ptr]+=1;
              ptr-=4;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr+=4;
                paper[ptr]-=1;
                ptr-=14;
                paper[ptr]+=1;
                ptr+=10;
              }
              ptr+=1;
            }
            ptr-=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=4;
              paper[ptr]+=1;
              ptr-=4;
            }
            ptr-=11;
          }
          ptr+=6;
          paper[ptr]+=1;
          ptr-=6;
        }
      }
      ptr+=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=4;
        paper[ptr]+=1;
        ptr+=4;
      }
      ptr-=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=4;
        paper[ptr]+=1;
        ptr+=5;
        while(paper[ptr]) {
          ptr+=9;
        }
        ptr-=9;
        while(paper[ptr]) {
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=5;
            paper[ptr]+=1;
            ptr-=4;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=4;
              paper[ptr]-=1;
              ptr-=14;
              paper[ptr]+=1;
              ptr+=11;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr+=3;
                paper[ptr]+=1;
                ptr-=3;
              }
              ptr-=1;
            }
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=3;
              paper[ptr]-=1;
              ptr-=14;
              paper[ptr]+=1;
              ptr+=11;
            }
            ptr-=2;
          }
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=4;
            paper[ptr]+=1;
            ptr-=3;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=3;
              paper[ptr]-=1;
              ptr-=14;
              paper[ptr]+=1;
              ptr+=11;
            }
            ptr-=1;
          }
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=3;
            paper[ptr]+=1;
            ptr-=3;
          }
          ptr-=12;
        }
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=2;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=5;
      while(paper[ptr]) {
        ptr+=2;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=6;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=4;
          paper[ptr]+=1;
          ptr+=4;
        }
        ptr-=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=4;
          paper[ptr]+=1;
          ptr-=3;
          paper[ptr]+=1;
          ptr-=1;
        }
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      paper[ptr]+=15;
      while(paper[ptr]) {
        while(paper[ptr]) {
          ptr+=9;
        }
        paper[ptr]+=1;
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr-=9;
        while(paper[ptr]) {
          ptr-=9;
        }
        ptr+=9;
        paper[ptr]-=1;
      }
      paper[ptr]+=1;
      while(paper[ptr]) {
        ptr+=1;
        paper[ptr]+=1;
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=1;
        paper[ptr]-=1;
        ptr+=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=4;
          paper[ptr]+=1;
          ptr+=4;
        }
        ptr-=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=4;
          paper[ptr]+=1;
          ptr-=5;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=2;
              paper[ptr]+=1;
              ptr+=2;
            }
            ptr-=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=2;
              paper[ptr]+=1;
              ptr+=1;
              paper[ptr]+=1;
              ptr-=3;
            }
            paper[ptr]+=1;
            ptr+=9;
          }
          ptr-=8;
          while(paper[ptr]) {
            ptr-=9;
          }
        }
        ptr+=9;
        while(paper[ptr]) {
          ptr+=9;
        }
        ptr-=9;
        while(paper[ptr]) {
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=9;
            paper[ptr]+=1;
            ptr-=9;
          }
          ptr-=10;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=9;
          paper[ptr]+=1;
          ptr-=9;
        }
        ptr-=1;
        paper[ptr]+=1;
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr-=1;
        paper[ptr]-=1;
        ptr+=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=3;
          paper[ptr]+=1;
          ptr+=1;
          while(paper[ptr]) {
            ptr-=1;
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]-=1;
            ptr-=7;
            paper[ptr]+=1;
            ptr+=7;
          }
          ptr-=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]+=1;
            ptr-=1;
          }
          ptr+=3;
        }
        ptr-=2;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=2;
          paper[ptr]+=1;
          ptr-=2;
        }
        ptr-=1;
        paper[ptr]+=1;
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=36;
          paper[ptr]+=1;
          ptr+=36;
        }
        ptr+=6;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=5;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=4;
      paper[ptr]+=15;
      while(paper[ptr]) {
        while(paper[ptr]) {
          ptr+=9;
        }
        ptr-=9;
        paper[ptr]-=1;
        ptr-=9;
        while(paper[ptr]) {
          ptr-=9;
        }
        ptr+=9;
        paper[ptr]-=1;
      }
      paper[ptr]+=1;
      while(paper[ptr]) {
        ptr+=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=3;
          paper[ptr]-=1;
          ptr+=3;
        }
        paper[ptr]+=1;
        ptr-=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=3;
          paper[ptr]-=1;
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=4;
            paper[ptr]+=1;
            ptr+=4;
          }
          ptr-=4;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=4;
            paper[ptr]+=1;
            ptr-=13;
            while(paper[ptr]) {
              ptr-=9;
            }
            ptr+=4;
            while(paper[ptr]) {
              paper[ptr]-=1;
            }
            paper[ptr]+=1;
            ptr+=5;
            while(paper[ptr]) {
              ptr+=9;
            }
            ptr+=1;
            paper[ptr]+=1;
            ptr-=1;
          }
        }
        paper[ptr]+=1;
        ptr+=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=4;
          paper[ptr]-=1;
          ptr+=4;
        }
        paper[ptr]+=1;
        ptr-=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=4;
          paper[ptr]-=1;
          ptr-=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=3;
            paper[ptr]+=1;
            ptr+=3;
          }
          ptr-=3;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=3;
            paper[ptr]+=1;
            ptr-=12;
            while(paper[ptr]) {
              ptr-=9;
            }
            ptr+=3;
            while(paper[ptr]) {
              paper[ptr]-=1;
            }
            paper[ptr]+=1;
            ptr+=6;
            while(paper[ptr]) {
              ptr+=9;
            }
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
            }
            paper[ptr]+=1;
            ptr-=1;
          }
        }
        paper[ptr]+=1;
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=1;
          while(paper[ptr]) {
            ptr+=9;
          }
          ptr-=8;
        }
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=3;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=3;
        paper[ptr]+=1;
        ptr+=3;
      }
      ptr-=3;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=3;
        paper[ptr]+=1;
        ptr+=6;
        while(paper[ptr]) {
          ptr+=1;
          paper[ptr]+=1;
          ptr+=3;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=3;
            paper[ptr]-=1;
            ptr+=3;
          }
          ptr-=3;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=3;
            paper[ptr]+=1;
            ptr-=3;
          }
          ptr+=8;
        }
        ptr-=8;
        paper[ptr]+=1;
        ptr-=1;
        while(paper[ptr]) {
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]+=1;
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=1;
              paper[ptr]-=1;
              ptr-=10;
              paper[ptr]+=1;
              ptr+=12;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr-=2;
                paper[ptr]+=1;
                ptr+=2;
              }
              ptr-=1;
            }
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=2;
              paper[ptr]-=1;
              ptr-=10;
              paper[ptr]+=1;
              ptr+=12;
            }
            ptr-=3;
          }
          ptr+=2;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=1;
            paper[ptr]+=1;
            ptr+=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=2;
              paper[ptr]-=1;
              ptr-=10;
              paper[ptr]+=1;
              ptr+=12;
            }
            ptr-=1;
          }
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=2;
            paper[ptr]+=1;
            ptr+=2;
          }
          ptr-=13;
        }
      }
      ptr+=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=4;
        paper[ptr]+=1;
        ptr+=4;
      }
      ptr-=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=4;
        paper[ptr]+=1;
        ptr+=5;
        while(paper[ptr]) {
          ptr+=1;
          paper[ptr]+=1;
          ptr+=2;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=2;
            paper[ptr]-=1;
            ptr+=2;
          }
          ptr-=2;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=2;
            paper[ptr]+=1;
            ptr-=2;
          }
          ptr+=8;
        }
        ptr-=8;
        paper[ptr]+=1;
        ptr-=1;
        while(paper[ptr]) {
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]+=1;
            ptr+=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=2;
              paper[ptr]-=1;
              ptr-=10;
              paper[ptr]+=1;
              ptr+=11;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr-=1;
                paper[ptr]+=1;
                ptr+=1;
              }
              ptr+=1;
            }
            ptr-=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=1;
              paper[ptr]-=1;
              ptr-=10;
              paper[ptr]+=1;
              ptr+=11;
            }
            ptr-=2;
          }
          ptr+=3;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=2;
            paper[ptr]+=1;
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=1;
              paper[ptr]-=1;
              ptr-=10;
              paper[ptr]+=1;
              ptr+=11;
            }
            ptr+=1;
          }
          ptr-=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=1;
            paper[ptr]+=1;
            ptr+=1;
          }
          ptr-=12;
        }
        ptr+=5;
        paper[ptr]+=1;
        ptr-=5;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=4;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=3;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=5;
      while(paper[ptr]) {
        ptr+=7;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=6;
          paper[ptr]+=1;
          ptr+=6;
        }
        ptr-=6;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=6;
          paper[ptr]+=1;
          ptr-=4;
          paper[ptr]+=1;
          ptr-=2;
        }
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=4;
      paper[ptr]+=1;
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=1;
        paper[ptr]-=1;
        ptr-=4;
        paper[ptr]+=1;
        ptr+=5;
      }
      ptr+=2;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=7;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=5;
          paper[ptr]+=1;
          ptr-=1;
          paper[ptr]+=2;
          ptr-=4;
        }
        ptr+=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=5;
          paper[ptr]+=1;
          ptr+=5;
        }
        ptr-=1;
        paper[ptr]-=1;
        ptr+=1;
        paper[ptr]+=1;
        ptr+=2;
      }
      ptr-=2;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=2;
        paper[ptr]+=1;
        ptr-=2;
      }
      ptr-=5;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=5;
        paper[ptr]+=1;
        ptr-=5;
      }
      paper[ptr]+=1;
      ptr+=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=4;
        paper[ptr]-=1;
        ptr+=4;
      }
      paper[ptr]+=1;
      ptr-=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=4;
        paper[ptr]-=1;
        ptr+=5;
        while(paper[ptr]) {
          ptr+=3;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=3;
            paper[ptr]-=1;
            ptr+=3;
          }
          paper[ptr]+=1;
          ptr-=3;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=3;
            paper[ptr]-=1;
            ptr-=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=2;
              paper[ptr]+=1;
              ptr+=2;
            }
            ptr-=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=2;
              paper[ptr]+=1;
              ptr-=11;
              while(paper[ptr]) {
                ptr-=9;
              }
              ptr+=4;
              while(paper[ptr]) {
                paper[ptr]-=1;
              }
              paper[ptr]+=1;
              ptr+=5;
              while(paper[ptr]) {
                ptr+=9;
              }
              ptr+=1;
              paper[ptr]+=1;
              ptr-=1;
            }
          }
          paper[ptr]+=1;
          ptr+=2;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=2;
            paper[ptr]-=1;
            ptr+=2;
          }
          paper[ptr]+=1;
          ptr-=2;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=2;
            paper[ptr]-=1;
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=3;
              paper[ptr]+=1;
              ptr+=3;
            }
            ptr-=3;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=3;
              paper[ptr]+=1;
              ptr-=12;
              while(paper[ptr]) {
                ptr-=9;
              }
              ptr+=3;
              while(paper[ptr]) {
                paper[ptr]-=1;
              }
              paper[ptr]+=1;
              ptr+=6;
              while(paper[ptr]) {
                ptr+=9;
              }
              ptr+=1;
              while(paper[ptr]) {
                paper[ptr]-=1;
              }
              paper[ptr]+=1;
              ptr-=1;
            }
          }
          paper[ptr]+=1;
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=1;
            while(paper[ptr]) {
              ptr+=9;
            }
            ptr-=8;
          }
          ptr+=8;
        }
        ptr-=9;
        while(paper[ptr]) {
          ptr-=9;
        }
        ptr+=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=3;
          paper[ptr]+=1;
          ptr+=3;
        }
        ptr-=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=3;
          paper[ptr]+=1;
          ptr+=6;
          while(paper[ptr]) {
            ptr+=1;
            paper[ptr]+=1;
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=1;
              paper[ptr]-=1;
              ptr+=1;
            }
            ptr-=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=1;
              paper[ptr]+=1;
              ptr-=1;
            }
            ptr+=8;
          }
          ptr-=8;
          paper[ptr]+=1;
          ptr-=1;
          while(paper[ptr]) {
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=4;
              paper[ptr]+=1;
              ptr-=2;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr+=2;
                paper[ptr]-=1;
                ptr-=13;
                paper[ptr]+=1;
                ptr+=10;
                while(paper[ptr]) {
                  paper[ptr]-=1;
                  ptr+=3;
                  paper[ptr]+=1;
                  ptr-=3;
                }
                ptr+=1;
              }
              ptr-=1;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr+=3;
                paper[ptr]-=1;
                ptr-=13;
                paper[ptr]+=1;
                ptr+=10;
              }
              ptr-=1;
            }
            ptr+=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=2;
              paper[ptr]+=1;
              ptr-=3;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr+=3;
                paper[ptr]-=1;
                ptr-=13;
                paper[ptr]+=1;
                ptr+=10;
              }
              ptr+=1;
            }
            ptr-=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=3;
              paper[ptr]+=1;
              ptr-=3;
            }
            ptr-=11;
          }
          ptr+=5;
          while(paper[ptr]) {
            paper[ptr]-=1;
          }
          ptr+=2;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=7;
            paper[ptr]+=1;
            ptr+=7;
          }
          ptr-=7;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=7;
            paper[ptr]+=1;
            ptr-=2;
            paper[ptr]+=1;
            ptr-=5;
          }
        }
        ptr+=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=4;
          paper[ptr]+=1;
          ptr+=4;
        }
        ptr-=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=4;
          paper[ptr]+=1;
          ptr+=5;
          while(paper[ptr]) {
            ptr+=1;
            paper[ptr]+=1;
            ptr+=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=2;
              paper[ptr]-=1;
              ptr+=2;
            }
            ptr-=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=2;
              paper[ptr]+=1;
              ptr-=2;
            }
            ptr+=8;
          }
          ptr-=8;
          paper[ptr]+=1;
          ptr-=1;
          while(paper[ptr]) {
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=4;
              paper[ptr]+=1;
              ptr-=3;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr+=3;
                paper[ptr]-=1;
                ptr-=13;
                paper[ptr]+=1;
                ptr+=11;
                while(paper[ptr]) {
                  paper[ptr]-=1;
                  ptr+=2;
                  paper[ptr]+=1;
                  ptr-=2;
                }
                ptr-=1;
              }
              ptr+=1;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr+=2;
                paper[ptr]-=1;
                ptr-=13;
                paper[ptr]+=1;
                ptr+=11;
              }
              ptr-=2;
            }
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=3;
              paper[ptr]+=1;
              ptr-=2;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr+=2;
                paper[ptr]-=1;
                ptr-=13;
                paper[ptr]+=1;
                ptr+=11;
              }
              ptr-=1;
            }
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=2;
              paper[ptr]+=1;
              ptr-=2;
            }
            ptr-=12;
          }
        }
        ptr+=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr-=4;
      }
      ptr+=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=4;
        paper[ptr]+=1;
        ptr+=4;
      }
      ptr-=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=4;
        paper[ptr]+=1;
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=2;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=7;
          paper[ptr]+=1;
          ptr+=7;
        }
        ptr-=7;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=7;
          paper[ptr]+=1;
          ptr-=2;
          paper[ptr]+=1;
          ptr-=5;
        }
        ptr+=9;
        while(paper[ptr]) {
          ptr+=9;
        }
        ptr-=9;
        while(paper[ptr]) {
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=4;
            paper[ptr]+=1;
            ptr-=3;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=3;
              paper[ptr]-=1;
              ptr-=13;
              paper[ptr]+=1;
              ptr+=11;
              while(paper[ptr]) {
                paper[ptr]-=1;
                ptr+=2;
                paper[ptr]+=1;
                ptr-=2;
              }
              ptr-=1;
            }
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=2;
              paper[ptr]-=1;
              ptr-=13;
              paper[ptr]+=1;
              ptr+=11;
            }
            ptr-=2;
          }
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=3;
            paper[ptr]+=1;
            ptr-=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=2;
              paper[ptr]-=1;
              ptr-=13;
              paper[ptr]+=1;
              ptr+=11;
            }
            ptr-=1;
          }
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=2;
            paper[ptr]+=1;
            ptr-=2;
          }
          ptr-=12;
        }
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=2;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=6;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=3;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=5;
      while(paper[ptr]) {
        ptr+=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=4;
          paper[ptr]+=1;
          ptr+=4;
        }
        ptr-=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=4;
          paper[ptr]+=1;
          ptr-=3;
          paper[ptr]+=1;
          ptr-=1;
        }
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=6;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=5;
          paper[ptr]+=1;
          ptr+=5;
        }
        ptr-=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=5;
          paper[ptr]+=1;
          ptr-=3;
          paper[ptr]+=1;
          ptr-=2;
        }
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      paper[ptr]+=15;
      while(paper[ptr]) {
        while(paper[ptr]) {
          ptr+=9;
        }
        paper[ptr]+=1;
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr-=9;
        while(paper[ptr]) {
          ptr-=9;
        }
        ptr+=9;
        paper[ptr]-=1;
      }
      paper[ptr]+=1;
      while(paper[ptr]) {
        ptr+=1;
        paper[ptr]+=1;
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=1;
        paper[ptr]-=1;
        ptr+=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=4;
          paper[ptr]+=1;
          ptr+=4;
        }
        ptr-=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=4;
          paper[ptr]+=1;
          ptr-=5;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=2;
              paper[ptr]+=1;
              ptr+=2;
            }
            ptr-=2;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=2;
              paper[ptr]+=1;
              ptr+=2;
              paper[ptr]+=1;
              ptr-=4;
            }
            paper[ptr]+=1;
            ptr+=9;
          }
          ptr-=8;
          while(paper[ptr]) {
            ptr-=9;
          }
        }
        ptr+=9;
        while(paper[ptr]) {
          ptr+=9;
        }
        ptr-=9;
        while(paper[ptr]) {
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=9;
            paper[ptr]+=1;
            ptr-=9;
          }
          ptr-=10;
        }
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=9;
          paper[ptr]+=1;
          ptr-=9;
        }
        ptr-=1;
        paper[ptr]+=1;
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr-=1;
        paper[ptr]-=1;
        ptr+=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=4;
          paper[ptr]+=1;
          ptr+=1;
          while(paper[ptr]) {
            ptr-=1;
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]-=1;
            ptr-=6;
            paper[ptr]+=1;
            ptr+=6;
          }
          ptr-=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]+=1;
            ptr-=1;
          }
          ptr+=4;
        }
        ptr-=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=3;
          paper[ptr]+=1;
          ptr-=3;
        }
        ptr-=1;
        paper[ptr]+=1;
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=1;
        paper[ptr]+=1;
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=1;
        paper[ptr]-=1;
        ptr+=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=5;
          paper[ptr]+=1;
          ptr+=5;
        }
        ptr-=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=5;
          paper[ptr]+=1;
          ptr-=6;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=3;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr-=3;
              paper[ptr]+=1;
              ptr+=3;
            }
            ptr-=3;
            while(paper[ptr]) {
              paper[ptr]-=1;
              ptr+=3;
              paper[ptr]+=1;
              ptr+=1;
              paper[ptr]+=1;
              ptr-=4;
            }
            paper[ptr]+=1;
            ptr+=9;
          }
          ptr-=8;
          while(paper[ptr]) {
            ptr-=9;
          }
        }
        ptr+=9;
        while(paper[ptr]) {
          ptr+=9;
        }
        ptr-=9;
        while(paper[ptr]) {
          ptr+=2;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=9;
            paper[ptr]+=1;
            ptr-=9;
          }
          ptr-=11;
        }
        ptr+=2;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=9;
          paper[ptr]+=1;
          ptr-=9;
        }
        ptr-=2;
        paper[ptr]+=1;
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr-=1;
        paper[ptr]-=1;
        ptr+=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=4;
          paper[ptr]+=1;
          ptr+=1;
          while(paper[ptr]) {
            ptr-=1;
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]-=1;
            ptr-=6;
            paper[ptr]+=1;
            ptr+=6;
          }
          ptr-=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]+=1;
            ptr-=1;
          }
          ptr+=4;
        }
        ptr-=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=3;
          paper[ptr]+=1;
          ptr-=3;
        }
        ptr-=1;
        paper[ptr]+=1;
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=36;
          paper[ptr]+=1;
          ptr+=36;
        }
        ptr+=5;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      paper[ptr]+=15;
      while(paper[ptr]) {
        while(paper[ptr]) {
          ptr+=9;
        }
        ptr-=9;
        paper[ptr]-=1;
        ptr-=9;
        while(paper[ptr]) {
          ptr-=9;
        }
        ptr+=9;
        paper[ptr]-=1;
      }
      paper[ptr]+=1;
      ptr+=21;
      paper[ptr]+=1;
      ptr-=3;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=3;
          paper[ptr]-=1;
          ptr+=3;
        }
        paper[ptr]+=1;
        ptr-=3;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=3;
          paper[ptr]-=1;
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=4;
            paper[ptr]+=1;
            ptr+=4;
          }
          ptr-=4;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=4;
            paper[ptr]+=1;
            ptr-=13;
            while(paper[ptr]) {
              ptr-=9;
            }
            ptr+=4;
            while(paper[ptr]) {
              paper[ptr]-=1;
            }
            paper[ptr]+=1;
            ptr+=5;
            while(paper[ptr]) {
              ptr+=9;
            }
            ptr+=1;
            paper[ptr]+=1;
            ptr-=1;
          }
        }
        paper[ptr]+=1;
        ptr+=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=4;
          paper[ptr]-=1;
          ptr+=4;
        }
        paper[ptr]+=1;
        ptr-=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=4;
          paper[ptr]-=1;
          ptr-=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=3;
            paper[ptr]+=1;
            ptr+=3;
          }
          ptr-=3;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=3;
            paper[ptr]+=1;
            ptr-=12;
            while(paper[ptr]) {
              ptr-=9;
            }
            ptr+=3;
            while(paper[ptr]) {
              paper[ptr]-=1;
            }
            paper[ptr]+=1;
            ptr+=6;
            while(paper[ptr]) {
              ptr+=9;
            }
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
            }
            paper[ptr]+=1;
            ptr-=1;
          }
        }
        paper[ptr]+=1;
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=1;
          while(paper[ptr]) {
            ptr+=9;
          }
          ptr-=8;
        }
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=2;
      paper[ptr]-=1;
      ptr+=2;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=4;
        paper[ptr]+=1;
        ptr+=4;
      }
      ptr-=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=4;
        paper[ptr]+=1;
        ptr-=2;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr-=2;
      }
      ptr+=2;
    }
    ptr-=2;
    paper[ptr]+=1;
    ptr+=4;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr-=4;
      paper[ptr]-=1;
      ptr+=4;
    }
    paper[ptr]+=1;
    ptr-=4;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr+=4;
      paper[ptr]-=1;
      ptr-=6;
      print(chr(paper[ptr]));
      ptr+=2;
    }
    ptr+=4;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr-=7;
      print(chr(paper[ptr]));
      ptr+=7;
    }
    ptr-=3;
    while(paper[ptr]) {
      paper[ptr]-=1;
    }
    ptr+=1;
    while(paper[ptr]) {
      paper[ptr]-=1;
    }
    ptr+=1;
    while(paper[ptr]) {
      paper[ptr]-=1;
    }
    ptr+=1;
    while(paper[ptr]) {
      paper[ptr]-=1;
    }
    ptr+=1;
    while(paper[ptr]) {
      paper[ptr]-=1;
    }
    ptr+=1;
    while(paper[ptr]) {
      paper[ptr]-=1;
    }
    ptr+=3;
    while(paper[ptr]) {
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=3;
    }
    ptr-=9;
    while(paper[ptr]) {
      ptr-=9;
    }
    ptr+=9;
    while(paper[ptr]) {
      ptr+=5;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=4;
    }
    ptr-=9;
    while(paper[ptr]) {
      ptr-=9;
    }
    ptr+=1;
    paper[ptr]+=11;
    while(paper[ptr]) {
      paper[ptr]-=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=9;
        paper[ptr]+=1;
        ptr-=9;
      }
      ptr+=9;
    }
    ptr+=4;
    paper[ptr]+=1;
    ptr+=9;
    paper[ptr]+=1;
    ptr-=14;
    while(paper[ptr]) {
      ptr-=9;
    }
    ptr+=7;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr-=7;
      paper[ptr]+=1;
      ptr+=7;
    }
    ptr-=7;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr+=7;
      paper[ptr]+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr+=2;
      while(paper[ptr]) {
        ptr+=9;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr+=7;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=6;
          paper[ptr]+=1;
          ptr+=6;
        }
        ptr-=6;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=6;
          paper[ptr]+=1;
          ptr-=7;
          while(paper[ptr]) {
            ptr-=9;
          }
          ptr+=7;
          while(paper[ptr]) {
            paper[ptr]-=1;
          }
          paper[ptr]+=1;
          ptr+=3;
        }
        ptr-=10;
      }
    }
    ptr+=7;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr-=7;
      paper[ptr]+=1;
      ptr+=7;
    }
    ptr-=7;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr+=7;
      paper[ptr]+=1;
      ptr+=2;
      while(paper[ptr]) {
        ptr+=1;
        paper[ptr]+=1;
        ptr+=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=4;
          paper[ptr]-=1;
          ptr+=4;
        }
        ptr-=4;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=4;
          paper[ptr]+=1;
          ptr-=4;
        }
        ptr+=8;
      }
      ptr-=2;
      paper[ptr]+=1;
      ptr-=7;
      while(paper[ptr]) {
        ptr+=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=2;
          paper[ptr]+=1;
          ptr-=2;
        }
        ptr-=14;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=9;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr-=1;
        paper[ptr]-=1;
        ptr+=7;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=7;
          paper[ptr]+=1;
          ptr+=1;
          while(paper[ptr]) {
            ptr-=1;
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]-=1;
            ptr-=3;
            paper[ptr]+=1;
            ptr+=3;
          }
          ptr-=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]+=1;
            ptr-=1;
          }
          ptr+=7;
        }
        ptr-=6;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=6;
          paper[ptr]+=1;
          ptr-=6;
        }
        ptr-=1;
        paper[ptr]+=1;
        ptr-=9;
      }
      ptr+=7;
      paper[ptr]-=1;
      ptr-=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      paper[ptr]+=1;
      ptr-=3;
    }
    paper[ptr]+=1;
    ptr+=7;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr-=7;
      paper[ptr]-=1;
      ptr+=7;
    }
    paper[ptr]+=1;
    ptr-=7;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr+=7;
      paper[ptr]-=1;
      ptr+=2;
      while(paper[ptr]) {
        ptr+=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=2;
          paper[ptr]+=1;
          ptr-=2;
        }
        ptr+=4;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        ptr-=1;
        paper[ptr]-=1;
        ptr+=7;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=7;
          paper[ptr]+=1;
          ptr+=1;
          while(paper[ptr]) {
            ptr-=1;
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]-=1;
            ptr-=3;
            paper[ptr]+=1;
            ptr+=3;
          }
          ptr-=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=1;
            paper[ptr]+=1;
            ptr-=1;
          }
          ptr+=7;
        }
        ptr-=6;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=6;
          paper[ptr]+=1;
          ptr-=6;
        }
        ptr-=1;
        paper[ptr]+=1;
        ptr-=9;
      }
      ptr+=1;
      paper[ptr]+=5;
      while(paper[ptr]) {
        paper[ptr]-=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=9;
          paper[ptr]+=1;
          ptr-=9;
        }
        ptr+=9;
      }
      ptr+=4;
      paper[ptr]+=1;
      ptr-=5;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=9;
      while(paper[ptr]) {
        ptr+=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=5;
          paper[ptr]-=1;
          ptr+=5;
        }
        paper[ptr]+=1;
        ptr-=5;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=5;
          paper[ptr]-=1;
          ptr+=2;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=7;
            paper[ptr]+=1;
            ptr+=7;
          }
          ptr-=7;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=7;
            paper[ptr]+=1;
            ptr-=16;
            while(paper[ptr]) {
              ptr-=9;
            }
            ptr+=4;
            while(paper[ptr]) {
              paper[ptr]-=1;
            }
            paper[ptr]+=1;
            ptr+=5;
            while(paper[ptr]) {
              ptr+=9;
            }
            ptr+=1;
            paper[ptr]+=1;
            ptr-=1;
          }
        }
        paper[ptr]+=1;
        ptr+=7;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=7;
          paper[ptr]-=1;
          ptr+=7;
        }
        paper[ptr]+=1;
        ptr-=7;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=7;
          paper[ptr]-=1;
          ptr-=2;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr-=5;
            paper[ptr]+=1;
            ptr+=5;
          }
          ptr-=5;
          while(paper[ptr]) {
            paper[ptr]-=1;
            ptr+=5;
            paper[ptr]+=1;
            ptr-=14;
            while(paper[ptr]) {
              ptr-=9;
            }
            ptr+=3;
            while(paper[ptr]) {
              paper[ptr]-=1;
            }
            paper[ptr]+=1;
            ptr+=6;
            while(paper[ptr]) {
              ptr+=9;
            }
            ptr+=1;
            while(paper[ptr]) {
              paper[ptr]-=1;
            }
            paper[ptr]+=1;
            ptr-=1;
          }
        }
        paper[ptr]+=1;
        ptr+=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=1;
          while(paper[ptr]) {
            ptr+=9;
          }
          ptr-=8;
        }
        ptr+=8;
      }
      ptr-=9;
      while(paper[ptr]) {
        ptr-=9;
      }
      ptr+=4;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr-=3;
      paper[ptr]+=5;
      while(paper[ptr]) {
        paper[ptr]-=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=9;
          paper[ptr]+=1;
          ptr-=9;
        }
        ptr+=9;
      }
      ptr+=4;
      paper[ptr]-=1;
      ptr-=5;
      while(paper[ptr]) {
        ptr-=9;
      }
    }
    ptr+=3;
  }
  ptr-=4;
  print(chr(paper[ptr]));
  ptr+=10;
  while(paper[ptr]) {
    ptr+=6;
    while(paper[ptr]) {
      paper[ptr]-=1;
    }
    ptr+=3;
  }
  ptr-=9;
  while(paper[ptr]) {
    ptr-=9;
  }
  ptr+=1;
  paper[ptr]+=10;
  while(paper[ptr]) {
    paper[ptr]-=1;
    while(paper[ptr]) {
      paper[ptr]-=1;
      ptr+=9;
      paper[ptr]+=1;
      ptr-=9;
    }
    ptr+=9;
  }
  ptr+=5;
  paper[ptr]+=1;
  ptr+=9;
  paper[ptr]+=1;
  ptr-=15;
  while(paper[ptr]) {
    ptr-=9;
  }
  ptr+=8;
  while(paper[ptr]) {
    paper[ptr]-=1;
    ptr-=8;
    paper[ptr]+=1;
    ptr+=8;
  }
  ptr-=8;
  while(paper[ptr]) {
    paper[ptr]-=1;
    ptr+=8;
    paper[ptr]+=1;
    while(paper[ptr]) {
      paper[ptr]-=1;
    }
    ptr+=1;
    while(paper[ptr]) {
      ptr+=9;
    }
    ptr-=9;
    while(paper[ptr]) {
      ptr+=8;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=7;
        paper[ptr]+=1;
        ptr+=7;
      }
      ptr-=7;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=7;
        paper[ptr]+=1;
        ptr-=8;
        while(paper[ptr]) {
          ptr-=9;
        }
        ptr+=8;
        while(paper[ptr]) {
          paper[ptr]-=1;
        }
        paper[ptr]+=1;
        ptr+=2;
      }
      ptr-=10;
    }
  }
  ptr+=8;
  while(paper[ptr]) {
    paper[ptr]-=1;
    ptr-=8;
    paper[ptr]+=1;
    ptr+=8;
  }
  ptr-=8;
  while(paper[ptr]) {
    paper[ptr]-=1;
    ptr+=8;
    paper[ptr]+=1;
    ptr+=1;
    while(paper[ptr]) {
      ptr+=1;
      paper[ptr]+=1;
      ptr+=5;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=5;
        paper[ptr]-=1;
        ptr+=5;
      }
      ptr-=5;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=5;
        paper[ptr]+=1;
        ptr-=5;
      }
      ptr+=8;
    }
    ptr-=1;
    paper[ptr]+=1;
    ptr-=8;
    while(paper[ptr]) {
      ptr+=6;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=2;
        paper[ptr]+=1;
        ptr-=2;
      }
      ptr-=15;
    }
    ptr+=9;
    while(paper[ptr]) {
      ptr+=9;
    }
    ptr-=9;
    while(paper[ptr]) {
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr-=1;
      paper[ptr]-=1;
      ptr+=8;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=8;
        paper[ptr]+=1;
        ptr+=1;
        while(paper[ptr]) {
          ptr-=1;
          paper[ptr]-=1;
          ptr+=1;
          paper[ptr]-=1;
          ptr-=2;
          paper[ptr]+=1;
          ptr+=2;
        }
        ptr-=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=1;
          paper[ptr]+=1;
          ptr-=1;
        }
        ptr+=8;
      }
      ptr-=7;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=7;
        paper[ptr]+=1;
        ptr-=7;
      }
      ptr-=1;
      paper[ptr]+=1;
      ptr-=9;
    }
    ptr+=8;
    paper[ptr]-=1;
    ptr-=5;
    while(paper[ptr]) {
      paper[ptr]-=1;
    }
    paper[ptr]+=1;
    ptr-=3;
  }
  paper[ptr]+=1;
  ptr+=8;
  while(paper[ptr]) {
    paper[ptr]-=1;
    ptr-=8;
    paper[ptr]-=1;
    ptr+=8;
  }
  paper[ptr]+=1;
  ptr-=8;
  while(paper[ptr]) {
    paper[ptr]-=1;
    ptr+=8;
    paper[ptr]-=1;
    ptr+=1;
    while(paper[ptr]) {
      ptr+=6;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=2;
        paper[ptr]+=1;
        ptr-=2;
      }
      ptr+=3;
    }
    ptr-=9;
    while(paper[ptr]) {
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
      }
      ptr-=1;
      paper[ptr]-=1;
      ptr+=8;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=8;
        paper[ptr]+=1;
        ptr+=1;
        while(paper[ptr]) {
          ptr-=1;
          paper[ptr]-=1;
          ptr+=1;
          paper[ptr]-=1;
          ptr-=2;
          paper[ptr]+=1;
          ptr+=2;
        }
        ptr-=1;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=1;
          paper[ptr]+=1;
          ptr-=1;
        }
        ptr+=8;
      }
      ptr-=7;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=7;
        paper[ptr]+=1;
        ptr-=7;
      }
      ptr-=1;
      paper[ptr]+=1;
      ptr-=9;
    }
    ptr+=1;
    paper[ptr]+=5;
    while(paper[ptr]) {
      paper[ptr]-=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=9;
        paper[ptr]+=1;
        ptr-=9;
      }
      ptr+=9;
    }
    ptr+=5;
    paper[ptr]+=1;
    ptr+=27;
    paper[ptr]+=1;
    ptr-=6;
    while(paper[ptr]) {
      ptr-=9;
    }
    ptr+=9;
    while(paper[ptr]) {
      ptr+=6;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=6;
        paper[ptr]-=1;
        ptr+=6;
      }
      paper[ptr]+=1;
      ptr-=6;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=6;
        paper[ptr]-=1;
        ptr+=2;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=8;
          paper[ptr]+=1;
          ptr+=8;
        }
        ptr-=8;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=8;
          paper[ptr]+=1;
          ptr-=17;
          while(paper[ptr]) {
            ptr-=9;
          }
          ptr+=4;
          while(paper[ptr]) {
            paper[ptr]-=1;
          }
          paper[ptr]+=1;
          ptr+=5;
          while(paper[ptr]) {
            ptr+=9;
          }
          ptr+=1;
          paper[ptr]+=1;
          ptr-=1;
        }
      }
      paper[ptr]+=1;
      ptr+=8;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=8;
        paper[ptr]-=1;
        ptr+=8;
      }
      paper[ptr]+=1;
      ptr-=8;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=8;
        paper[ptr]-=1;
        ptr-=2;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr-=6;
          paper[ptr]+=1;
          ptr+=6;
        }
        ptr-=6;
        while(paper[ptr]) {
          paper[ptr]-=1;
          ptr+=6;
          paper[ptr]+=1;
          ptr-=15;
          while(paper[ptr]) {
            ptr-=9;
          }
          ptr+=3;
          while(paper[ptr]) {
            paper[ptr]-=1;
          }
          paper[ptr]+=1;
          ptr+=6;
          while(paper[ptr]) {
            ptr+=9;
          }
          ptr+=1;
          while(paper[ptr]) {
            paper[ptr]-=1;
          }
          paper[ptr]+=1;
          ptr-=1;
        }
      }
      paper[ptr]+=1;
      ptr+=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr-=1;
        while(paper[ptr]) {
          ptr+=9;
        }
        ptr-=8;
      }
      ptr+=8;
    }
    ptr-=9;
    while(paper[ptr]) {
      ptr-=9;
    }
    ptr+=4;
    while(paper[ptr]) {
      paper[ptr]-=1;
    }
    ptr-=3;
    paper[ptr]+=5;
    while(paper[ptr]) {
      paper[ptr]-=1;
      while(paper[ptr]) {
        paper[ptr]-=1;
        ptr+=9;
        paper[ptr]+=1;
        ptr-=9;
      }
      ptr+=9;
    }
    ptr+=5;
    paper[ptr]-=1;
    ptr+=27;
    paper[ptr]-=1;
    ptr-=6;
    while(paper[ptr]) {
      ptr-=9;
    }
  }
  ptr+=3;
}
